name: Pull new changes on main for implanchihuauha.org 

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Aplicar cambios del repositorio en el servidor.
        run: |
          git config --global --add safe.directory /var/www/html
          
          cd /var/www/html

          git pull origin main